version: '3'
services:
  backstage:
    image: backstage
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      # Add your token here
      GITHUB_TOKEN: <INSERT_GITHUB_TOKEN>
      SPOTIFY_PLUGIN_LICENSE: <INSERT_LICENSE_KEY>
      PAGERDUTY_TOKEN: <INSERT_PAGERDUTY_TOKEN>
      SONARQUBE_HOST: <INSERT_SONARQUBE_HOST>
      SONARQUBE_TOkEN: <INSERT_SONARQUBE_TOKEN>
      DATADOG_HOST: <INSERT_DATADOG_HOST>
      DATADOG_APP_KEY: <INSERT_DATADOG_APP_KEY>
      DATADOG_API_KEY: <INSERT_DATADOG_API_KEY>
    ports:
      - '7007:7007'
    volumes:
      - ./soundcheck:/app/soundcheck
      - ./examples/:/app/examples
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
